language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0

services:
  - mysql

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install

script: vendor/bin/phpunit

matrix:
  allow_failures:
    - php: 5.6
  fast_finish: true